name: Deploy static content to Pages
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare docs directory
        run: |
          rm -rf docs
          mkdir docs
          cp -r src/* docs/
          # Create both .nojekyll and CNAME files
          touch docs/.nojekyll
          echo "mydomain.dev" > docs/CNAME
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
